### ISSUE TITLE
bash: ./morningo-installer: cannot execute binary file: 可执行文件格式错误

### ISSUE THREAD

**Issue by datafeng** [chenhg5/morningo#1]
bash: ./morningo-installer: cannot execute binary file: 可执行文件格式错误

**Comment by chenhg5** [comment]
```
wget https://gitee.com/cg33/morningo-installer/raw/master/morningo-installer-linus    # linus
./morningo-installer-linus
```

**Comment by datafeng** [comment]
嗯可以安装了，但同步包的时候又zz了：）
——————————————————————————
root@ubuntu:~/go/src/web# make deps
go get github.com/kardianos/govendor
govendor sync
make: govendor：命令未找到
Makefile:33: recipe for target 'deps' failed
make: *** [deps] Error 127
————————————————————————
ubuntu16.4系统，我发现govendor被安装到go/bin/目录下了，不是安装到我$goroot下面。


# **上面的问题都解决了。
make test的时候出问题了**
root@ubuntu:~/go/src/web# make test
go test -v ./
panic: Error 1045: Access denied for user 'root'@'localhost' (using password: YES)

goroutine 1 [running]:
web/models.init.0()
	/root/go/src/web/models/Model.go:17 +0x1e5
FAIL	web	0.008s
Makefile:16: recipe for target 'test' failed
make: *** [test] Error 1
root@ubuntu:~/go/src/web#

**Comment by chenhg5** [comment]
@fhq 需要配置一下数据库连接信息。`config/env.go`这个文件里面，有个数据结构例子在`connections/migrations/example.sql`
