### ISSUE TITLE
./morningo-installer-linus --project-name web Error

### ISSUE THREAD

**Issue by SpiffyEight77** [chenhg5/morningo#2]
Ubuntu 16.04
./morningo-installer-linus --morningo web 
./morningo-installer-linus: 2: ./morningo-installer-linus: Syntax error: newline unexpected

**Comment by chenhg5** [comment]
@SpiffyEight77 试试这个 https://gitee.com/cg33/morningo-installer/raw/master/morningo-installer-ubuntu

**Comment by zqhong** [comment]
```
wget https://gitee.com/cg33/morningo-installer/raw/master/morningo-installer
```

我这边使用 macOS 系统，执行上面的命令，返回的是 HTML 页面。提示：文件大于1M，登录后可见

**Comment by q920447939** [comment]
可以加下QQ或者微信讨论吗?

**Comment by chenhg5** [comment]
@q920447939 可以的 qq群 756664859

**Comment by Kirk-Wang** [comment]
@q920447939 模板非常cool，我也弄了一个 template，[Ten-Minutes-App](https://github.com/lotteryjs/Ten-Minutes-App)
